packages:
  - "packages/client"
  - "packages/proto"

# Only allow installing packages that are at least a day old
minimumReleaseAge: 1440
# Allow depending on just published ChronoQueue packages
minimumReleaseAgeExclude:
  - "@chronoqueue/*"

ignoreScripts: true
